version: "3.8"

services:
  cdp:
    build:
      context: ../..
    image: cdp:dev
    volumes:
      - .:/app
    command: ["-e", "/app/pipeline.yaml"]
    ports:
      - 8001:8001
      - 8002:8002

  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - 9090:9090

volumes:
  prometheus:
