---
name: "Event exposition"

input:
  generator: exposition_example

jsonnet-prelude: |-
  local eventPipeline(event) =
    event.t[std.length(event.t) - 1].p;

  local eventSignature(event) =
    event.t[std.length(event.t) - 1].h;

steps:
  expose for prometheus:
    flatmap:
      expose-http:
        endpoint: /metrics
        port: 8002
        responses: 100
        headers:
          Content-Type: text/plain; version=0.0.4
        jsonnet-expr: |-
          function(events)
            "# TYPE " + events[0].n + " gauge\n" +
            std.join(
              "\n",
              std.map(
                function(event)
                  event.n +
                  "{pipeline=\"" + eventPipeline(event) + "\"," +
                  "signature=\"" + eventSignature(event) + "\"} " +
                  std.toString(event.d),
                events
              )
            ) +
            "\n"
