name: "Basic jq transformations"
input:
  stdin:
steps:
  # Two types of steps are illustrated: jq transformations and stdout
  # forwarding (with and without jq).

  duplicate-and-wrap:
    window:
      events: 100
      seconds: 1
    reduce:
      send-receive-jq: |-
        map([. * {
          n: (.n + ".given"),
          d: {value: .d}
        }] + (if .d == null then [] else [. * {
          n: (.n + ".healthy"),
          d: .d
        }] end))

  show-only-healthy:
    after:
      - duplicate-and-wrap
    match/drop: "#.healthy"
    flatmap:
      send-stdout:

  show-all-names:
    after:
      - duplicate-and-wrap
    flatmap:
      send-stdout:
        jq-expr: ".[].n"
