x-cdp: &cdp
  build:
    context: ../..
  image: cdp:dev
  volumes:
    - .:/app
    - bridge:/shared

version: "3.8"

services:
  first:
    <<: *cdp
    command: ["/app/pipeline-first.yaml"]
    ports:
      - 8000:8000
    depends_on:
      - second

  second:
    <<: *cdp
    command: ["-e", "/app/pipeline-second.yaml"]
    environment:
      TARGET: http://third:8000/events
    depends_on:
      - third

  third:
    <<: *cdp
    command: ["/app/pipeline-third.yaml"]
    expose:
      - "8002"

  fourth:
    <<: *cdp
    command: ["-e", "/app/pipeline-fourth.yaml"]
    environment:
      SOURCE: http://third:8002/events
    depends_on:
      - third

volumes:
  bridge:
