version: "3.8"

services:
  cdp:
    build:
      context: ../..
    image: cdp:dev
    environment:
      HTTP_CLIENT_REJECT_UNAUTHORIZED: "false" # OpenSearch demo can't provide valid certificates
    volumes:
      - .:/app
      - shared-logs:/var/log/shared-logs
    command: ["-e", "/app/pipeline.yaml"]
    ports:
      - 8001:8001
    depends_on:
      - nginx

  nginx:
    build:
      dockerfile: nginx.Dockerfile
    volumes:
      - shared-logs:/var/log/nginx

  bot:
    image: alpine:3.15
    command:
      - /bin/sh
      - -c
      - |-
        while :
        do
          wget -O- http://nginx
          sleep .5
        done

  opensearch:
    image: opensearchproject/opensearch:1.3.1
    environment:
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.0
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'

volumes:
  shared-logs:
  opensearch-data:
